version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      # ignore major version updates for slugify to keep in line with eleventy
      - dependency-name: "@sindresorhus/slugify"
        update-types: ["version-update:semver-major"]
    groups:
      dev-dependencies:
        patterns:
          - "stylelint*"
