[dev]
autoLaunch = false

[[redirects]]
from = "/all-questions/:questionNumber/"
to = "/.netlify/builders/on-demand"
status = 200
force = true
_generated_by_eleventy_serverless = "on-demand"

[[redirects]]
from = "/"
to = "/.netlify/builders/on-demand"
status = 200
force = true
_generated_by_eleventy_serverless = "on-demand"

[[redirects]]
from = "/questions/:tag/:questionNumber/"
to = "/.netlify/builders/on-demand"
status = 200
force = true
_generated_by_eleventy_serverless = "on-demand"

[[redirects]]
from = "/categories/:tag/"
to = "/.netlify/builders/on-demand"
status = 200
force = true
_generated_by_eleventy_serverless = "on-demand"
