[dev]
autoLaunch = false

[[redirects]]
from = "/flash-cards/:tag/:questionNumber/"
to = "/.netlify/builders/on-demand"
status = 200
force = true
_generated_by_eleventy_serverless = "on-demand"

[[redirects]]
from = "/all/flash-cards/:questionNumber/"
to = "/.netlify/builders/on-demand"
status = 200
force = true
_generated_by_eleventy_serverless = "on-demand"

[[redirects]]
from = "/"
to = "/.netlify/builders/on-demand"
status = 200
force = true
_generated_by_eleventy_serverless = "on-demand"
