[dev]
autoLaunch = false

[[redirects]]
from = "/dynamic/"
to = "/.netlify/functions/dynamic"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamic"

[[redirects]]
from = "/on-demand/"
to = "/.netlify/builders/on-demand"
status = 200
force = true
_generated_by_eleventy_serverless = "on-demand"
