[dev]
autoLaunch = false

[[redirects]]
from = "/dynamic/"
to = "/.netlify/functions/dynamic"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamic"

[[redirects]]
from = "/serverless/"
to = "/.netlify/builders/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"
